name: Deploy
on:
  push:
    branches:
      - master

jobs:

  build:
    name: Running deploy.sh
    runs-on: ubuntu-latest
    steps:
    - name: Running deploy.sh 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script_stop: true
        script: /root/minijobs/deploy.sh